# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, guys!

dotenv: [".env"]

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - go-task -l
    silent: true

  setup:
    desc: crate folder to store data
    cmds:
      - mkdir -p data/raw/empty data/raw/right data/raw/wrong
      - mkdir -p data/train/empty data/train/right data/train/wrong
      - mkdir -p data/validation/empty data/validation/right data/validation/wrong

  data:rm:
    desc: remove folder with data
    cmds:
      - rm -rf data/raw

  data:push:
    desc: push data to dvc (gdrive)
    cmds:
      - task: data:rm
      - .venv/bin/dvc push

  data:zip:
    desc: unzip data and model
    cmds:
      - rm data/raw.zip
      - cd ./data; zip -r raw.zip raw models CHANGELOG.md; cd ..

  data:fetch:
    cmds:
      - task: data:rm
      - .venv/bin/dvc pull
      - unzip data/raw.zip -d data

  venv:
    desc: create/update venv
    cmds:
      - python -m venv .venv --prompt checkedbox
      - task: venv:update
      - task: git:hooks
    status:
      - test -d .venv

  venv:update:
    desc: update the virtual environment
    cmds:
      - .venv/bin/pip install -U pdm pip mypy pre-commit
      - .venv/bin/pip install -e ./
      - .venv/bin/pip install -r requirements.txt
    preconditions:
      - test -d .venv
      - msg: "missing virtual env"

  git:hooks:
    desc: install pre-commit
    cmds:
      - .venv/bin/pre-commit install --hook-type pre-commit --hook-type pre-merge-commit --hook-type post-merge
    preconditions:
      - test -d .venv
      - msg: "missing virtual env"
